name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Show directory structure
        run: ls -la

      - name: Install dependencies
        run: npm install

      - name: Debug page components
        run: |
          echo "Checking for page components:"
          ls -la src/pages || echo "Pages directory not found"

      - name: Build project
        run: |
          npm run build
          touch dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist